version: '3.4'

services:
  messagebroker:
    image: rabbitmq:management
  shipdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  stockdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  statemachineworkerdb:
     image: mcr.microsoft.com/mssql/server:2019-latest

  orderservice:
    image: cuongnguyen161202/orderservice:latest

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile


  shipservice:
    image: shipservice
    build:
      context: .
      dockerfile: ShipService/Dockerfile


  statemachineworkerservice:
    image: statemachineworkerservice
    build:
      context: .
      dockerfile: StateMachineWorkerService/Dockerfile


  stockservice:
    image: stockservice
    build:
      context: .
      dockerfile: StockService/Dockerfile
  nginx:
      image: nginx:latest
volumes: #Container içerisindeki verilerin kalıcı olması için volume kullanıyoruz.
  shipdb_volume:
  stockdb_volume:
  statemachineworkerdb_volume:
  orderdb_volume: