version: '3.4'

services:
  orderdb:
    container_name: order-mssql-database
    restart: always
    ports:
      - 1443:1433
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  shipdb:
    container_name: ship-mssql-database
    restart: always
    ports:
      - 1444:1433
    volumes:
      - shipdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  stockdb:
    container_name: stock-mssql-database
    restart: always
    ports:
      - 1445:1433
    volumes:
      - stockdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  statemachineworkerdb:
    container_name: statemachineworker-mssql-database
    restart: always
    ports:
      - 1446:1433
    volumes:
      - statemachineworkerdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ConnectionStrings__AppDbContext=Server=orderdb,1433;Database=MicroServiceDb;User=sa;Password=Password123;TrustServerCertificate=True
      - RabbitMqSetting__HostAddress=amqp://ecommerce-mq:5672
      - RabbitMqSetting__Username=guest
      - RabbitMqSetting__Password=guest
    depends_on:
      - messagebroker
      - orderdb
    ports:
      - "5001:80"
      - "5051:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  paymentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - RabbitMqSetting__HostAddress=amqp://ecommerce-mq:5672
      - RabbitMqSetting__Username=guest
      - RabbitMqSetting__Password=guest
    depends_on:
      - messagebroker
    ports:
      - "5002:8080"
      - "5052:8081"
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  shipservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AppDbContext=Server=shipdb,1433;Database=ShipService;User=sa;Password=Password123;TrustServerCertificate=True
      - RabbitMqSetting__HostAddress=amqp://ecommerce-mq:5672
      - RabbitMqSetting__Username=guest
      - RabbitMqSetting__Password=guest
    depends_on:
      - messagebroker
      - shipdb
    ports:
      - "5003:8080"
      - "5053:8081"
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  statemachineworkerservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__OrderStateDbContext=Server=statemachineworkerdb,1433;Database=SagaDB;User=sa;Password=Password123;TrustServerCertificate=True
      - RabbitMqSetting__HostAddress=amqp://ecommerce-mq:5672
      - RabbitMqSetting__Username=guest
      - RabbitMqSetting__Password=guest
    depends_on:
      - messagebroker
      - statemachineworkerdb
  stockservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AppDbContext=Server=stockdb,1433;Database=StockService;User=sa;Password=Password123;TrustServerCertificate=True
      - RabbitMqSetting__HostAddress=amqp://ecommerce-mq:5672
      - RabbitMqSetting__Username=guest
      - RabbitMqSetting__Password=guest
    depends_on:
      - messagebroker
      - stockdb
    ports:
      - "5004:8080"
      - "5054:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  nginx:
      image: nginx:latest
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "/d/ely.nguyen/learn/dotnet core/Microservices/nginx.conf:/etc/nginx/nginx.conf:ro"  # Mount your Nginx config
        - "/d/ely.nguyen/learn/dotnet core/Microservices/privkey.pem:/etc/nginx/certs/privkey.pem:ro"
        - "/d/ely.nguyen/learn/dotnet core/Microservices/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro"
      depends_on:
        - orderservice
